# bundle install
# bundle exec jekyll serve
# https://pages.github.com/versions/

# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# jekyll new --skip-bundle .

# aws s3 cp --recursive s3://myBucket/dir localdir
# aws s3 sync s3://mybucket/dir localdir

# https://github.com/jekyll/minima

title: Anas Najaa Blog
author:
    name: Anas Najaa
    email: anas@najaa.org
email: anas@najaa.org
description: >- # this means to ignore newlines until "baseurl:"
    Thoughts of a digital nomad.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anasnajaa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: anasnajaa
google_analytics: G-13QRFBM8TT

# Build settings
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

social_links:
    - { platform: github, user_url: "https://github.com/anasnajaa" }
    #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
    #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
    #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
    #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
